### PR TITLE
refactor: cli: refactor entire cli

### PR DESCRIPTION
**Pull request by Suyashtnt**
haha yes

### CODE REVIEW

**Comment by Suyashtnt** [comment]
time to redo tests

**Comment by Milo123459** [comment]
I believe you have to rebase or something because some changes I made (specifically using the crate `which`) aren't included in your branch.

Thanks for the PR :)

**Comment by Suyashtnt** [comment]
> I believe you have to rebase or something because some changes I made (specifically using the crate `which`) aren't included in your branch.
> 
> Thanks for the PR :)

thats weird bc its in the cargo.toml

**Comment by Milo123459** [comment]
> > I believe you have to rebase or something because some changes I made (specifically using the crate `which`) aren't included in your branch.
> > Thanks for the PR :)
> 
> thats weird bc its in the cargo.toml

uh...
sorry that I'm blind

**Comment by Milo123459** [comment]
Also would you mind taking a look at #34? Thanks

**Comment by Suyashtnt** [comment]
> Also would you mind taking a look at #34? Thanks

yeah no that sadly aint happening

**Comment by Milo123459** [comment]
Hey @Suyashtnt - any updates on this PR? If there aren't any I'll close it.

**Pull request closed without merging**
