### PR TITLE
Add commit `action` and `no-add` flag

### PR DESCRIPTION
**Pull request by Strosel**
This PR adds the `commit` action for committing without pushing as well as the `-no-add` flag for suppressing `git add .` in favour of adding changes by hand in case of split commits

### CODE REVIEW

**Comment by Milo123459** [comment]
I think I'd prefer to keep it as one command, and have a flag like `-a` so that a new command isn't introduced.

**Comment by Strosel** [comment]
Could you specify exactly what you mean please. With the current setup -no-add applies to both commit and push and as such I don't feel like it qualifies as it's own command.

**Comment by Milo123459** [comment]
I want to remove glitter commit ideally. I don't see it doing anything else. Or, if you want to keep it, it could be made as an alias instead.

**Comment by Milo123459** [comment]
I'm okay with the no-add flag, just could you make `commit` an alias of `push`? Rather than adding an entirely new command.

**Comment by Strosel** [comment]
I think I'd rather remove glitter commit than making it an alias of push since commit is not the same as commit + push and having that aliased could be considered misleading for users

**Pull request closed without merging**
